### ISSUE TITLE
Using the custom RDKit version but still KeyError: 'molAtomMapNumber'

### ISSUE THREAD

**Issue by GhostSteven** [connorcoley/ochem_predict_nn#7]
Great Work! I'm trying to run the already-trained model lowe_interactive_predict.py. I've already installed and used the custom version of RDKit but I still get this Error:

```
Traceback (most recent call last):
  File "lowe_interactive_predict.py", line 255, in <module>
    candidate_list = reactants_to_candidate_edits(reactants)
  File "lowe_interactive_predict.py", line 64, in reactants_to_candidate_edits
    raise(e)
KeyError: 'molAtomMapNumber'
```

I can't figure it out for a long time. What should I do to solve it or find where is wrong?

BTW, I use the Mongodb for the first time and I imported the data from your **dump** with inputting in the console like that:

 mongo restore -d prediction <./../dump/prediction>

is that right?

**Comment by connorcoley** [comment]
Have you tried using the verbose setting to see the outcome SMILES string? (https://github.com/connorcoley/ochem_predict_nn/blob/master/scripts/lowe_interactive_predict.py#L50) I'm wondering if you're accidentally using the non-custom version of RDKit and so your outcome doesn't have its atom mapping defined. You could also try checking where the RDKit installation is to make sure it's the custom one by looking at the ```rdkit.__path__``` attribute after importing rdkit in a python shell.

That should be the right syntax for the Mongo restore, although I'll admit it's been a while since I've used that command

**Comment by GhostSteven** [comment]
Thank you very much. 
There was only one outcome SMILE string generated which corresponding to the first template. And the __path__ is also right.
Now I'm trying to run your **rexgen_direct** instead of this model. And maybe after that I will try to figure out what's wrong with the rdkit. I guess it may be some parts' version problem or something during configuring the release.

**Comment by bxs0906** [comment]
Hello, I also encountered the same problem, can I communicate with you. thank you very much.
Looking forward to your reply.
